apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-ingress-devops
  namespace: haproxy-controller-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      containers:
        - name: ingress-container-devops
          image: haproxytech/kubernetes-ingress
          args:
            - "--default-backend-service=haproxy-controller-devops/service-backend-devops"
          resources:
            requests:
              cpu: 500m
              memory: 50Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 1024
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 1024
              name: stat
          env:
            - name: TZ
              value: "Etc/UTC"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
