apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
            name: db-secret
