apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: webapp-container
      image: nginx
      volumeMounts:
        - name: nginx-log
          mountPath: /var/log/nginx
  volumes:
    - name: nginx-log
      persistentVolumeClaim:
        claimName: claim-log-1
